version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/myapp

hooks:
   ApplicationStop:
    - location: scripts/stop_docker.sh
      timeout: 180
      runas: root
   AfterInstall:
    - location: scripts/install_nginx.sh
      timeout: 180
      runas: root         # changed from ubuntu
   ApplicationStart:
    - location: scripts/start_nginx.sh
      timeout: 180
      runas: root         # changed from ubuntu
